---
- name: Remove apache2
  yum: name=apache2 state=absent
  sudo: True
  tags: install

- name: Remove nginx
  yum: name=nginx state=absent
  sudo: True
  tags: install

  
- name: Install rubygems,  nginx
  action: yum pkg={{ item }} state=installed
  sudo: True
  with_items:
   - rubygems
   - nginx 
  tags: install


- name: Install passenger via gem
  command: gem install passenger
  tags: install


- name: Copy nginx configuration
  copy:
    src=nginx.conf
    dest=/etc/nginx/nginx.conf
    owner=root
    group=root
    mode=0644
    backup=yes
  sudo: True
  tags: configure


- name: Copy passenger start script
  copy:
    src=standalone-start.sh
    dest=/home/ec2-user/standalone-start.sh
    mode=0744

- name: Start passenger standalone via script 
  command: /home/ec2-user/standalone-start.sh
  tags: configure


- name: Start nginx
  service: name=nginx state=restarted
  tags: configure

